[package]
name = "iter"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
workspace = "../../"
edition = "2018"

[dependencies]
bit-set = "0.5.2"

[features]
default = []
unstable = []
